### ISSUE TITLE
Bug in testing the current day and typos

### ISSUE THREAD

**Issue by Adrian-Rosoga** [Arvic68/better-bat-check#1]
GetCurruntDay() at line 75 is tested against the list of days outside the while loop.
It should be inside and tested every time, else if the program is started on Saturday (or a day nor in a list) it won't "speak".

Typos:
# Currunt should be Current
# check_speed could better be renamed check_interval_secs
# Check failed message is misleading. Nothing failed in fact, just the battery is above the threshold.

**Comment by Adrian-Rosoga** [comment]
No idea why it came in huge bold font.

**Comment by Arvic68** [comment]
Fixed all issues and added some color to new.py
Please reinstall requirements.txt
